-- SQLite
CREATE TABLE EMPLOYEES(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  PHONE TEXT NOT NULL,
  CONTRACT_DATE TEXT NOT NULL,
  POSITION_ID INTEGER NOT NULL,
  
  FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS (ID)
)