-- SQLite
CREATE TABLE CUSTOMERS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME VARCHAR(100) NOT NULL,
  LASTNAME TEXT NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  ADDRESS TEXT NOT NULL,
  CITY TEXT NOT NULL,
  STATE VARCHAR(2) NOT NULL,
  BIRTH_DATE TEXT NOT NULL
);