-- SQLite
SELECT START_DATE, END_DATE, TOTAL, EMPLOYEES.NAME as EMPLOYEE_NAME, CUSTOMERS.NAME as CUSTOMER_FIRST_NAME, CARS.NAME as CAR_NAME
FROM LOCATIONS
INNER JOIN CUSTOMERS ON CUSTOMERS.id = LOCATIONS.CUSTOMER_ID
INNER JOIN EMPLOYEES ON EMPLOYEES.id = LOCATIONS.EMPLOYEE_ID
INNER JOIN CARS ON CARS.id = LOCATIONS.CAR_ID

-- Mostra o número total de locações da tabela locations
SELECT COUNT(*) AS NUMBER_OF_LOCATIONS
FROM LOCATIONS

-- Mostra a locação de maior valor da tabela locations
SELECT *
FROM LOCATIONS
ORDER BY TOTAL DESC
LIMIT 1

-- Seleciona as locações entre as datas desejadas
SELECT *
FROM LOCATIONS
WHERE START_DATE >= '2022-05-20' AND START_DATE <= '2022-12-25'